### ISSUE TITLE
Not working in Spigot 1.11

### ISSUE THREAD

**Issue by TNTUP** [ShadowDog007/Horses#4]
NOTE: This is a copypasta issue I made on this bukkitdev's plugin page ticket section.

What steps will reproduce the problem?
1. Setup a test server on Spigot 1.11 with the Horses 1.1.15
2. Buy a Horse
3. Summon it and watch console.

What is the expected output? What do you see instead?

Summoning the requested horse.

Stack trace.

What version of the product are you using?

Horses 1.1.15

Do you have an error log of what happened?

[16:33:24 INFO]: TNTUP issued server command: /h s
[16:33:29 WARN]: [Horses] Task #4647 for Horses v1.1.15 generated an exception
java.lang.UnsupportedOperationException Not supported.
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at com.forgenz.horses.HorseType.setHorseType(HorseType.java:141) ~[?:?]
        at com.forgenz.horses.PlayerHorse.spawnHorse(PlayerHorse.java:425) ~[?:?]
        at com.forgenz.horses.command.SummonCommand$1.run(SummonCommand.java:186) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Please provide any additional information below.

This will prevent me upgrading to 1.11 if this plugin gets not fixed. Having this plugin since Mojang added Horses on my server. Wont change on another horses plugin losing everyone horses

**Comment by TNTUP** [comment]
Activity here: https://dev.bukkit.org/bukkit-plugins/horse-stables/?comment=1049 

If anyone uses this plugin, this is good news for 1.11

**Comment by TNTUP** [comment]
@ShadowDog007 If you're still active on Github, mind fixing bugs in 1.11.2 and fix your build script aswell? Even, your 1.9 is outdated, why not to 1.11.2's jar? I'll close this issue tho its related to 1.1.15 not .19. I'll maybe open another issue if you care about your users who used your plugin and even donated to your project.
